name: Publish
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  publish:
    name: Publish
    runs-on: [self-hosted, AWS, Linux]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Assume role
        if: github.ref == 'refs/heads/main'
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: "arn:aws:iam::022062736489:role/r+<%= githubOrg %>+<%= repoName %>+repo"
          role-duration-seconds: 3600
          aws-region: ca-central-1

      - name: Publish
        uses: BrightspaceUI/actions/publish-to-s3@main
        with:
          bucket-path: s3://d2l.dev/<%= subdomain %>/main
          publish-directory: ./dist/
